repos:
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks: [id: black]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks: [id: flake8]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks: [id: mypy]

  - repo: local
    hooks:
      - id: pytest
        name: pytest (fast)
        entry: pytest -q
        language: system     # використовує той самий venv
        pass_filenames: false
