version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:8000"
    env_file: .env
    command: >
      sh -c "python manage.py migrate &&
             gunicorn company_site.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: company_db
      POSTGRES_USER: company_user
      POSTGRES_PASSWORD: company_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
