version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./staticfiles:/app/staticfiles
    command: gunicorn company_site.wsgi:application -b 0.0.0.0:8000

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: company_db
      POSTGRES_USER: company_user
      POSTGRES_PASSWORD: company_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
