version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: company_db
      POSTGRES_USER: company_user
      POSTGRES_PASSWORD: company_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8000"
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn company_site.wsgi:application --bind 0.0.0.0:8000
      "

volumes:
  postgres_data:
