# Generated by Django 5.0.14 on 2025-05-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["title"],
                "verbose_name": "Послуга",
                "verbose_name_plural": "Послуги",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, verbose_name="Опис"),
        ),
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AddField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                verbose_name="Ціна, $",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=120, verbose_name="Назва послуги"),
        ),
    ]
