name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Перевіряємо код
      - uses: actions/checkout@v4

      # 2) Встановлюємо Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3) Інсталяція залежностей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Лінт та тести
      - name: Lint
        run: |
          black --check .
          flake8 .
          mypy .
      - name: Run tests
        run: pytest -q

      # 5) Встановлюємо Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl -sL https://cli-assets.heroku.com/install.sh | sh

      # 6) Автоматичний деплой на Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email:      ${{ secrets.HEROKU_EMAIL }}
          usedocker: false
