name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Django & dev tools
        run: |
          pip install -r requirements.txt
          pip install black flake8 mypy pytest pytest-django whitenoise
      - name: Lint: black
        run: black --check .
      - name: Lint: flake8
        run: flake8 .
      - name: Typecheck: mypy
        run: mypy .
      - name: Test: pytest
        run: pytest --maxfail=1 --disable-warnings -qq
